markdown: kramdown
highlighter: rouge
theme: jekyll-theme-minimal
plugins:
  - jekyll-coffeescript
title : Silon
author :
  name : Tim Menzies
  email : timm@ieee.org
  github : timm
  twitter : timmenzies

