plugins:
  - jekyll-coffeescript

author :
  name : Tim Menzies
  email : timm@ieee.org
  github : timm
  twitter : timmenzies

title: 'SILON'
logo: /assets/img/cylon.png
google_analytics:
theme: jekyll-theme-minimal
description: |
   Cluster, contrast, dominate, control

incremental: true
highlighter: rouge
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

