title: 'SILON- v0.1'
logo: /assets/img/cylon.png
google_analytics:
highlighter: pygments
theme: jekyll-theme-minimal
description: >
  Cluster, contrast, dominate, control
  <p>
  here1:
    <a href="one">one</a> |
    <a href="two">two</a> |
    <a href="two">two</a> |
    <a href="two">two</a> |
    <a href="three">three</a> <br>there1:
    <a href="four">four</a> |
    <a href="five">five</a> |
    <a href="five">five</a> |
    <a href="five">five</a> |
    <a href="six">six</a> 
  </p>
   
