title: 'SILON- v0.1'
logo: /assets/img/cylon.png
google_analytics:
theme: jekyll-theme-minimal
description: >
  Cluster, contrast, dominate, control <br>
  here:
    <a href="adsa">one<a>
    <a href="adsa">two<a>
    <a href="adsa">three<a><br>
  there:
    <a href="adsa">one<a>
    <a href="adsa">two<a>
    <a href="adsa">three<a>
  <br clear=all>
   
